version: '3'

services:
  slurm:
    build: .
    hostname: slurmctl
    container_name: slurmy
    cap_add: ['sys_admin']
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/lib:/var/lib/slurmd
      - ./volumes/spool:/var/spool/slurm
      - ./volumes/log:/var/log/slurm
      - ./volumes/db:/var/lib/mysql
